# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '3.0.100-preview3-010431'
    packageType: sdk

- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test tests\Services\StoryBlog.Tests.Services.Data.Csv\StoryBlog.Tests.Services.Data.Csv.csproj  --configuration $(buildConfiguration) --logger trx
  displayName: 'dotnet build $(buildConfiguration)'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: NuGetCommand@2
  displayName: 'Nuget push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'myFeed'
    versioningScheme: 'off'